FROM node:12.16.3-alpine

RUN addgroup -S app && adduser -S app -G app

ENV HOME=/home/app

COPY backend/package*.json $HOME/<%=project_slug%>/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/<%=project_slug%>
RUN npm install

CMD ["npm", "start"]
