FROM node:18.16-alpine

RUN addgroup -S app && adduser -S app -G app

RUN apk update \
  && apk add mongodb-tools

ENV HOME=/home/app

COPY backend/package*.json $HOME/<%=project_slug%>/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/<%=project_slug%>
RUN npm install

CMD ["npm", "start"]
