FROM node:10.15.0-alpine

RUN addgroup -S app && adduser -S app -G app
RUN apk update && apk upgrade \
	&& apk --no-cache add --virtual builds-deps build-base python

ENV HOME=/home/app

COPY package.json package-lock.json $HOME/{{cookiecutter.project_slug}}/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/{{cookiecutter.project_slug}}
RUN npm install

RUN npm rebuild bcrypt --build-from-source

CMD ["npm", "start"]
